# Generated by Django 5.1.2 on 2024-10-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='residence_ID',
            new_name='residence',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='student_ID',
            new_name='student',
        ),
    ]
