# Generated by Django 5.1.2 on 2024-10-20 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_rename_faculty_name_faculty_faculty'),
        ('student', '0005_alter_application_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.housingadmin'),
        ),
    ]
