# Generated by Django 5.1.2 on 2024-10-20 10:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_ID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('faculty_name', models.CharField(choices=[('Accounting and Informatics', 'Accounting and Informatics'), ('Applied Sciences', 'Applied Sciences'), ('Management Sciences', 'Management Sciences'), ('Engineering and the Built Environment', 'Engineering and the Built Environment'), ('Health Sciences', 'Health Sciences'), ('Arts & Design', 'Arts & Design')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HousingAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_ID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('cell_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_ID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('residence_name', models.CharField(max_length=100)),
                ('total_num_of_rooms', models.IntegerField()),
                ('residence_address', models.CharField(max_length=255)),
                ('distance_to_campus', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_ID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('room_type', models.CharField(choices=[('1-sleeper', '1-sleeper'), ('2-sleeper', '2-sleeper')], max_length=10)),
                ('bed_count', models.IntegerField()),
                ('available_beds', models.IntegerField()),
            ],
        ),
    ]
